//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serkanISG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILDIRIMLVL1
    {
        public int ID_BILDIRIM { get; set; }
        public string TARIHSAAT { get; set; }
        public string PERSONEL_AD { get; set; }
        public string KATEGORI { get; set; }
        public string ACIKLAMA { get; set; }
        public string ONLEMBOOL { get; set; }
        public string LOKASYON { get; set; }
        public string BIRIM { get; set; }
        public string AKSIYON { get; set; }
        public string DURUM { get; set; }
        public string BILDIRIM_DURUM { get; set; }
        public string VARDIYA { get; set; }
        public string MUDAHIL_PERSONEL { get; set; }
        public string GORSEL { get; set; }
    }
}
