//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serkanISG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIRIM
    {
        public int ID_BIRIM { get; set; }
        public string AD_BIRIM { get; set; }
        public string DURUM_BIRIM { get; set; }
    }
}
