//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serkanISG
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODUL_MAILAYAR
    {
        public int ID_MODUL { get; set; }
        public string AD_MODUL { get; set; }
        public string YENI_KAYIT { get; set; }
        public string GUNCELLEME_KAYIT { get; set; }
        public string SILME_KAYIT { get; set; }
    }
}
