//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serkanISG
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL
    {
        public int PERSONEL_ID { get; set; }
        public string PERSONEL_AD { get; set; }
        public string PERSONEL_SOYAD { get; set; }
        public Nullable<int> SICIL_NO { get; set; }
        public string YAPTIGI_IS { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string SIFRE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> IS_BASLANGIC_TARIH { get; set; }
        public string Rol { get; set; }
        public string TCNO { get; set; }
        public string BIRIM_PERSONEL { get; set; }
        public string UNVAN_PERSONEL { get; set; }
        public string LOKASYON_PERSONEL { get; set; }
    }
}
