//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serkanISG
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYGUNSUZLUK
    {
        public int ID_UYGUNSUZLUK { get; set; }
        public string AKTIFLIK { get; set; }
        public string TUR { get; set; }
        public string UYGUNSUZ_DURUM { get; set; }
        public Nullable<System.DateTime> TESPIT_TARIH { get; set; }
        public string SORUMLU_AD { get; set; }
        public string TESPIT_EDEN_AD { get; set; }
        public Nullable<System.DateTime> TERMIN_TARIH { get; set; }
        public string ONERI_AKSIYON { get; set; }
        public string BIRIM { get; set; }
        public Nullable<int> TESPIT_EDEN_ID { get; set; }
        public Nullable<int> SORUMLU_ID { get; set; }
        public byte[] FOTO { get; set; }
    }
}
