<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Kullanicilar.aspx.cs" Inherits="serkanISG.Kullanicilar" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <link href="../Content/MyCSS.css" rel="stylesheet" />
    <script src="../Scripts/MyFunctions.js"></script>
    <script src="../Scripts/ddlJs.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
  
    <style>
        /*!
Chosen, a Select Box Enhancer for jQuery and Prototype
by Patrick Filler for Harvest, http://getharvest.com

Version 1.8.7
Full source at https://github.com/harvesthq/chosen
Copyright (c) 2011-2018 Harvest http://getharvest.com

MIT License, https://github.com/harvesthq/chosen/blob/master/LICENSE.md
This file is generated by `grunt build`, do not edit it by hand.
*/

/* @group Base */
.chosen-container {
  position: relative;
  display: inline-block;
  vertical-align: middle;
  font-size: 13px;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
}

.chosen-container * {
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
}

.chosen-container .chosen-drop {
  position: absolute;
  top: 100%;
  z-index: 1010;
  width: 100%;
  border: 1px solid #aaa;
  border-top: 0;
  background: #fff;
  -webkit-box-shadow: 0 4px 5px rgba(0, 0, 0, 0.15);
          box-shadow: 0 4px 5px rgba(0, 0, 0, 0.15);
  clip: rect(0, 0, 0, 0);
  -webkit-clip-path: inset(100% 100%);
          clip-path: inset(100% 100%);
}

.chosen-container.chosen-with-drop .chosen-drop {
  clip: auto;
  -webkit-clip-path: none;
          clip-path: none;
}

.chosen-container a {
  cursor: pointer;
}

.chosen-container .search-choice .group-name, .chosen-container .chosen-single .group-name {
  margin-right: 4px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  font-weight: normal;
  color: #999999;
}

.chosen-container .search-choice .group-name:after, .chosen-container .chosen-single .group-name:after {
  content: ":";
  padding-left: 2px;
  vertical-align: top;
}

/* @end */
/* @group Single Chosen */
.chosen-container-single .chosen-single {
  position: relative;
  display: block;
  overflow: hidden;
  padding: 0 0 0 8px;
  height: 25px;
  border: 1px solid #aaa;
  border-radius: 5px;
  background-color: #fff;
  background: -webkit-gradient(linear, left top, left bottom, color-stop(20%, #fff), color-stop(50%, #f6f6f6), color-stop(52%, #eee), to(#f4f4f4));
  background: linear-gradient(#fff 20%, #f6f6f6 50%, #eee 52%, #f4f4f4 100%);
  background-clip: padding-box;
  -webkit-box-shadow: 0 0 3px #fff inset, 0 1px 1px rgba(0, 0, 0, 0.1);
          box-shadow: 0 0 3px #fff inset, 0 1px 1px rgba(0, 0, 0, 0.1);
  color: #444;
  text-decoration: none;
  white-space: nowrap;
  line-height: 24px;
}

.chosen-container-single .chosen-default {
  color: #999;
}

.chosen-container-single .chosen-single span {
  display: block;
  overflow: hidden;
  margin-right: 26px;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.chosen-container-single .chosen-single-with-deselect span {
  margin-right: 38px;
}

.chosen-container-single .chosen-single abbr {
  position: absolute;
  top: 6px;
  right: 26px;
  display: block;
  width: 12px;
  height: 12px;
  background: url("chosen-sprite.png") -42px 1px no-repeat;
  font-size: 1px;
}

.chosen-container-single .chosen-single abbr:hover {
  background-position: -42px -10px;
}

.chosen-container-single.chosen-disabled .chosen-single abbr:hover {
  background-position: -42px -10px;
}

.chosen-container-single .chosen-single div {
  position: absolute;
  top: 0;
  right: 0;
  display: block;
  width: 18px;
  height: 100%;
}

.chosen-container-single .chosen-single div b {
  display: block;
  width: 100%;
  height: 100%;
  background: url("chosen-sprite.png") no-repeat 0px 2px;
}

.chosen-container-single .chosen-search {
  position: relative;
  z-index: 1010;
  margin: 0;
  padding: 3px 4px;
  white-space: nowrap;
}

.chosen-container-single .chosen-search input[type="text"] {
  margin: 1px 0;
  padding: 4px 20px 4px 5px;
  width: 100%;
  height: auto;
  outline: 0;
  border: 1px solid #aaa;
  background: url("chosen-sprite.png") no-repeat 100% -20px;
  font-size: 1em;
  font-family: sans-serif;
  line-height: normal;
  border-radius: 0;
}

.chosen-container-single .chosen-drop {
  margin-top: -1px;
  border-radius: 0 0 4px 4px;
  background-clip: padding-box;
}

.chosen-container-single.chosen-container-single-nosearch .chosen-search {
  position: absolute;
  clip: rect(0, 0, 0, 0);
  -webkit-clip-path: inset(100% 100%);
          clip-path: inset(100% 100%);
}

/* @end */
/* @group Results */
.chosen-container .chosen-results {
  color: #444;
  position: relative;
  overflow-x: hidden;
  overflow-y: auto;
  margin: 0 4px 4px 0;
  padding: 0 0 0 4px;
  max-height: 240px;
  -webkit-overflow-scrolling: touch;
}

.chosen-container .chosen-results li {
  display: none;
  margin: 0;
  padding: 5px 6px;
  list-style: none;
  line-height: 15px;
  word-wrap: break-word;
  -webkit-touch-callout: none;
}

.chosen-container .chosen-results li.active-result {
  display: list-item;
  cursor: pointer;
}

.chosen-container .chosen-results li.disabled-result {
  display: list-item;
  color: #ccc;
  cursor: default;
}

.chosen-container .chosen-results li.highlighted {
  background-color: #3875d7;
  background-image: -webkit-gradient(linear, left top, left bottom, color-stop(20%, #3875d7), color-stop(90%, #2a62bc));
  background-image: linear-gradient(#3875d7 20%, #2a62bc 90%);
  color: #fff;
}

.chosen-container .chosen-results li.no-results {
  color: #777;
  display: list-item;
  background: #f4f4f4;
}

.chosen-container .chosen-results li.group-result {
  display: list-item;
  font-weight: bold;
  cursor: default;
}

.chosen-container .chosen-results li.group-option {
  padding-left: 15px;
}

.chosen-container .chosen-results li em {
  font-style: normal;
  text-decoration: underline;
}

/* @end */
/* @group Multi Chosen */
.chosen-container-multi .chosen-choices {
  position: relative;
  overflow: hidden;
  margin: 0;
  padding: 0 5px;
  width: 100%;
  height: auto;
  border: 1px solid #aaa;
  background-color: #fff;
  background-image: -webkit-gradient(linear, left top, left bottom, color-stop(1%, #eee), color-stop(15%, #fff));
  background-image: linear-gradient(#eee 1%, #fff 15%);
  cursor: text;
}

.chosen-container-multi .chosen-choices li {
  float: left;
  list-style: none;
}

.chosen-container-multi .chosen-choices li.search-field {
  margin: 0;
  padding: 0;
  white-space: nowrap;
}

.chosen-container-multi .chosen-choices li.search-field input[type="text"] {
  margin: 1px 0;
  padding: 0;
  height: 25px;
  outline: 0;
  border: 0 !important;
  background: transparent !important;
  -webkit-box-shadow: none;
          box-shadow: none;
  color: #999;
  font-size: 100%;
  font-family: sans-serif;
  line-height: normal;
  border-radius: 0;
  width: 25px;
}

.chosen-container-multi .chosen-choices li.search-choice {
  position: relative;
  margin: 3px 5px 3px 0;
  padding: 3px 20px 3px 5px;
  border: 1px solid #aaa;
  max-width: 100%;
  border-radius: 3px;
  background-color: #eeeeee;
  background-image: -webkit-gradient(linear, left top, left bottom, color-stop(20%, #f4f4f4), color-stop(50%, #f0f0f0), color-stop(52%, #e8e8e8), to(#eee));
  background-image: linear-gradient(#f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eee 100%);
  background-size: 100% 19px;
  background-repeat: repeat-x;
  background-clip: padding-box;
  -webkit-box-shadow: 0 0 2px #fff inset, 0 1px 0 rgba(0, 0, 0, 0.05);
          box-shadow: 0 0 2px #fff inset, 0 1px 0 rgba(0, 0, 0, 0.05);
  color: #333;
  line-height: 13px;
  cursor: default;
}

.chosen-container-multi .chosen-choices li.search-choice span {
  word-wrap: break-word;
}

.chosen-container-multi .chosen-choices li.search-choice .search-choice-close {
  position: absolute;
  top: 4px;
  right: 3px;
  display: block;
  width: 12px;
  height: 12px;
  background: url("chosen-sprite.png") -42px 1px no-repeat;
  font-size: 1px;
}

.chosen-container-multi .chosen-choices li.search-choice .search-choice-close:hover {
  background-position: -42px -10px;
}

.chosen-container-multi .chosen-choices li.search-choice-disabled {
  padding-right: 5px;
  border: 1px solid #ccc;
  background-color: #e4e4e4;
  background-image: -webkit-gradient(linear, left top, left bottom, color-stop(20%, #f4f4f4), color-stop(50%, #f0f0f0), color-stop(52%, #e8e8e8), to(#eee));
  background-image: linear-gradient(#f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eee 100%);
  color: #666;
}

.chosen-container-multi .chosen-choices li.search-choice-focus {
  background: #d4d4d4;
}

.chosen-container-multi .chosen-choices li.search-choice-focus .search-choice-close {
  background-position: -42px -10px;
}

.chosen-container-multi .chosen-results {
  margin: 0;
  padding: 0;
}

.chosen-container-multi .chosen-drop .result-selected {
  display: list-item;
  color: #ccc;
  cursor: default;
}

/* @end */
/* @group Active  */
.chosen-container-active .chosen-single {
  border: 1px solid #5897fb;
  -webkit-box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
          box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
}

.chosen-container-active.chosen-with-drop .chosen-single {
  border: 1px solid #aaa;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
  background-image: -webkit-gradient(linear, left top, left bottom, color-stop(20%, #eee), color-stop(80%, #fff));
  background-image: linear-gradient(#eee 20%, #fff 80%);
  -webkit-box-shadow: 0 1px 0 #fff inset;
          box-shadow: 0 1px 0 #fff inset;
}

.chosen-container-active.chosen-with-drop .chosen-single div {
  border-left: none;
  background: transparent;
}

.chosen-container-active.chosen-with-drop .chosen-single div b {
  background-position: -18px 2px;
}

.chosen-container-active .chosen-choices {
  border: 1px solid #5897fb;
  -webkit-box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
          box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
}

.chosen-container-active .chosen-choices li.search-field input[type="text"] {
  color: #222 !important;
}

/* @end */
/* @group Disabled Support */
.chosen-disabled {
  opacity: 0.5 !important;
  cursor: default;
}

.chosen-disabled .chosen-single {
  cursor: default;
}

.chosen-disabled .chosen-choices .search-choice .search-choice-close {
  cursor: default;
}

/* @end */
/* @group Right to Left */
.chosen-rtl {
  text-align: right;
}

.chosen-rtl .chosen-single {
  overflow: visible;
  padding: 0 8px 0 0;
}

.chosen-rtl .chosen-single span {
  margin-right: 0;
  margin-left: 26px;
  direction: rtl;
}

.chosen-rtl .chosen-single-with-deselect span {
  margin-left: 38px;
}

.chosen-rtl .chosen-single div {
  right: auto;
  left: 3px;
}

.chosen-rtl .chosen-single abbr {
  right: auto;
  left: 26px;
}

.chosen-rtl .chosen-choices li {
  float: right;
}

.chosen-rtl .chosen-choices li.search-field input[type="text"] {
  direction: rtl;
}

.chosen-rtl .chosen-choices li.search-choice {
  margin: 3px 5px 3px 0;
  padding: 3px 5px 3px 19px;
}

.chosen-rtl .chosen-choices li.search-choice .search-choice-close {
  right: auto;
  left: 4px;
}

.chosen-rtl.chosen-container-single .chosen-results {
  margin: 0 0 4px 4px;
  padding: 0 4px 0 0;
}

.chosen-rtl .chosen-results li.group-option {
  padding-right: 15px;
  padding-left: 0;
}

.chosen-rtl.chosen-container-active.chosen-with-drop .chosen-single div {
  border-right: none;
}

.chosen-rtl .chosen-search input[type="text"] {
  padding: 4px 5px 4px 20px;
  background: url("chosen-sprite.png") no-repeat -30px -20px;
  direction: rtl;
}

.chosen-rtl.chosen-container-single .chosen-single div b {
  background-position: 6px 2px;
}

.chosen-rtl.chosen-container-single.chosen-with-drop .chosen-single div b {
  background-position: -12px 2px;
}

/* @end */
/* @group Retina compatibility */
@media only screen and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-resolution: 144dpi), only screen and (min-resolution: 1.5dppx) {
  .chosen-rtl .chosen-search input[type="text"],
  .chosen-container-single .chosen-single abbr,
  .chosen-container-single .chosen-single div b,
  .chosen-container-single .chosen-search input[type="text"],
  .chosen-container-multi .chosen-choices .search-choice .search-choice-close,
  .chosen-container .chosen-results-scroll-down span,
  .chosen-container .chosen-results-scroll-up span {
    background-image: url("chosen-sprite@2x.png") !important;
    background-size: 52px 37px !important;
    background-repeat: no-repeat !important;
  }
}

/* @end */

    </style>




    <div class="pd-ltr-20 xs-pd-20-10" style="margin-left: 5%; width: 1317px;">
        <div class="min-height-200px">

            <!-- Simple Datatable start -->
            <div class="card-box mb-190">
                <div class="pd-20" style="margin-top: 100px">
                    <h4 class="text-blue h4 text-center">KULLANICI LİSTESİ</h4>
                </div>
            </div>
            <br />
            <ul>
                <li>
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myyModal">Yeni Kullanıcı Ekle</button>


                </li>

            </ul>
            <br />
            <div style="width: 100%; height: 450px; overflow: scroll">
                <asp:GridView ID="grdKullanici" CssClass="data-table table stripe hover nowrap" AutoGenerateColumns="False" GridLines="None" runat="server">
                    <Columns>
                        <asp:TemplateField HeaderText="Düzen">
                            <ItemTemplate>
                                <asp:LinkButton runat="server" CssClass="btn btn-warning" ID="link" CausesValidation="false" OnClick="link_Click" CommandName="Select" CommandArgument='<%# Eval("PERSONEL_ID") %>'>Düzenle</asp:LinkButton>
                                <asp:LinkButton runat="server" CssClass="btn btn-danger" ID="btn_sil" OnClientClick="return fnConfirmDelete();" CausesValidation="false" OnClick="btn_sil_Click" CommandArgument='<%# Eval("PERSONEL_ID") %>'>Sil</asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="SICIL_NO" HeaderText="Sicil Numarası" />
                        <asp:BoundField DataField="PERSONEL_ID" HeaderText="Kullanıcı ID" />
                        <asp:BoundField DataField="PERSONEL_AD" HeaderText="Ad" />
                        <asp:BoundField DataField="PERSONEL_SOYAD" HeaderText="Soyad" />
                        <asp:BoundField DataField="KULLANICI_ADI" HeaderText="Kullanıcı Adı" />
                        <asp:BoundField DataField="UNVAN_PERSONEL" HeaderText="Unvan" />
                        <asp:BoundField DataField="BIRIM_PERSONEL" HeaderText="Birim" />
                        <asp:BoundField DataField="LOKASYON_PERSONEL" HeaderText="Lokasyon" />
                    </Columns>
                </asp:GridView>
            </div>
            <div id="myModal" class="modal" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg " role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Kategori Tanım Düzenleme Ekranı</h5>
                            <button type="button" id="uptKapa" onclick="baseUrl();" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">


                            <div class="card">
                                <div style="background-color: aquamarine" class="card-header">
                                    Kullanıcı Bilgileri
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label class="form-group-item">Personel Adı*</label>
                                            <asp:DropDownList CssClass=" form-control" AppendDataBoundItems="true" ID="ddlPersonel_Edit" runat="server">
                                                <asp:ListItem Text="Seçiniz" />
                                            </asp:DropDownList>
                                        </div>
                                        <div class="col-md-6">
                                            <br />
                                            <br />
                                            <asp:CompareValidator ID="CompareValidator3" Style="font-weight: 700;" ForeColor="red" ControlToValidate="ddlPersonel" Type="string" ValueToCompare="Seçiniz" Operator="NotEqual" runat="server" ErrorMessage="Lütfen Personel Seçiniz*">
                                        
                                            </asp:CompareValidator>
                                        </div>
                                    </div>
                                    <br />
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label class="form-group-item">Kullanıcı Adı*</label>
                                            <asp:TextBox ID="txtUserNameEdit" CssClass="form-control" runat="server"></asp:TextBox>

                                        </div>
                                        <div class="col-md-6">
                                            <br />
                                            <br />
                                            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" Style="font-weight: 700;" ForeColor="red" runat="server" ControlToValidate="txtUsername" ErrorMessage="Bu alan zorunludur*"></asp:RequiredFieldValidator>
                                        </div>
                                    </div>
                                    <br />
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label class="form-group-item">Unvan</label>
                                            <asp:DropDownList AppendDataBoundItems="true" CssClass=" form-control" ID="ddlUnvanEdit" runat="server">
                                                <asp:ListItem Text="Seçiniz" />
                                            </asp:DropDownList>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="card">
                                <div style="background-color: aquamarine" class="card-header">
                                    Profiller
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <br />
                                        <div class="col-md-6">

                                            <asp:CheckBoxList ID="ckblProfilEdit" CssClass="form-check" runat="server">
                                                <asp:ListItem Value="IsgUzmn" Text="&nbsp;&nbsp;Isg Uzmanı" onclick="MutExChkList(this)" />
                                                <asp:ListItem Value="Admin" Text="&nbsp;&nbsp;Admin" onclick="MutExChkList(this)" />
                                                <asp:ListItem Value="genel" Text="&nbsp;&nbsp;Genel Kullanıcı" onclick="MutExChkList(this)" />
                                            </asp:CheckBoxList>
                                        </div>
                                        <div class="col-md-6">
                                            <asp:CustomValidator ForeColor="red" Style="font-weight: 700;" ClientValidationFunction="ValidateCheckBoxList" ID="CustomValidator3" runat="server" ErrorMessage="Lütfen Profil Seçiniz*"></asp:CustomValidator>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div style="background-color: aquamarine" class="card-header">
                                    Birimler
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <br />
                                        <div class="col-md-6">

                                            <asp:CheckBoxList CellSpacing="213" ID="ckblBirimEdit" CssClass="chkChoice" runat="server">
                                            </asp:CheckBoxList>
                                        </div>
                                        <div class="col-md-6">
                                            <asp:CustomValidator ForeColor="red" Style="font-weight: 700;" ClientValidationFunction="ValidateBirim" ID="CustomValidator4" runat="server" ErrorMessage="Lütfen Birim Seçiniz*"></asp:CustomValidator>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div style="background-color: aquamarine" class="card-header">
                                    Lokasyonlar
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <br />
                                        <div class="col-md-6">

                                            <asp:DropDownList AppendDataBoundItems="true" ID="ddlLokasyonEdit" CssClass="form-control" runat="server">
                                                <asp:ListItem Text="Seçiniz" />
                                            </asp:DropDownList>
                                        </div>
                                        <div class="col-md-6">

                                            <asp:CompareValidator ID="CompareValidator4" Style="font-weight: 700;" ForeColor="red" ControlToValidate="ddlLokasyon" Type="string" ValueToCompare="Seçiniz" Operator="NotEqual" runat="server" ErrorMessage="Lütfen Person Seçiniz*">
                                        
                                            </asp:CompareValidator>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <%--sd --%>
                        </div>
                        <div class="modal-footer">
                            <button type="button" onclick="baseUrl();" class="btn btn-secondary" id="uptVaz" data-dismiss="modal">Kapat</button>
                            <asp:Button Text="Güncelle" CausesValidation="false" OnClick="edit_Kaydet_Click" ID="edit_Kaydet" class="btn btn-success" runat="server" />

                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>



    <!-- Button trigger modal -->


    <!-- Modal -->
    <div class="modal fade" id="myyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Kullanıcı Tanımlama Ekranı</h4>
                    <button type="button" onclick="baseUrl();" id="kapa" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                </div>
                <div class="modal-body">
                    <div class="card">
                        <div style="background-color: aquamarine" class="card-header">
                            Kullanıcı Bilgileri
                        </div>
                        <div class="card-body">
                            <div class="row">
                              
                            </div>
                           
                            <div class="row">
                                  <div class="col-md-6">

                                       <label class="col-md-12 form-group-item">Deneme</label>
                                        <asp:DropDownList AppendDataBoundItems="true" CssClass="col-md-12" ID="ddllist" runat="server">
                                              <asp:ListItem Text="Seçiniz" />
                                        </asp:DropDownList>

                                    </div>
                                     <script>    
                                        $('#<%=ddllist.ClientID%>').chosen();
                                       <%--  $('#<%=ddllist.ClientID%>').css("width", "200px");--%>

                                         $('#MainContent_ddllist_chosen').css("width", "400px");
                                    

            


                                         //$('#MainContent_ddllist_chosen').removeClass("form-control");
                                        
                                         



                                     </script>
                          
                           </div>
                           
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    <label class="form-group-item">Personel Adı*</label>
                                    <asp:DropDownList AppendDataBoundItems="true" CssClass="form-control" ID="ddlPersonel" runat="server">
                                        <asp:ListItem Text="Seçiniz" />
                                    </asp:DropDownList>
                                  

                                </div>
                                <div class="col-md-6">
                                    <br />
                                    <br />
                                    <asp:CompareValidator ID="CompareValidator1" Style="font-weight: 700;" ForeColor="red" ControlToValidate="ddlPersonel" Type="string" ValueToCompare="Seçiniz" Operator="NotEqual" runat="server" ErrorMessage="Lütfen Personel Seçiniz*">
                                        
                                    </asp:CompareValidator>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    <label class="form-group-item">Kullanıcı Adı*</label>
                                    <asp:TextBox ID="txtUsername" CssClass="form-control" runat="server"></asp:TextBox>

                                </div>
                                <div class="col-md-6">
                                    <br />
                                    <br />
                                    <asp:RequiredFieldValidator ID="userValid" Style="font-weight: 700;" ForeColor="red" runat="server" ControlToValidate="txtUsername" ErrorMessage="Bu alan zorunludur*"></asp:RequiredFieldValidator>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    <label class="form-group-item">Unvan</label>
                                    <asp:DropDownList AppendDataBoundItems="true" CssClass=" form-control" ID="ddlUnvan" runat="server">
                                        <asp:ListItem Text="Seçiniz" />
                                    </asp:DropDownList>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="card">
                        <div style="background-color: aquamarine" class="card-header">
                            Profiller
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <br />
                                <div class="col-md-6">

                                    <asp:CheckBoxList ID="ckblProfil" CssClass="form-check" runat="server">
                                        <asp:ListItem Value="IsgUzmn" Text="&nbsp;&nbsp;Isg Uzmanı" onclick="MutExChkList(this)" />
                                        <asp:ListItem Value="Admin" Text="&nbsp;&nbsp;Admin" onclick="MutExChkList(this)" />
                                        <asp:ListItem Value="genel" Text="&nbsp;&nbsp;Genel Kullanıcı" onclick="MutExChkList(this)" />
                                    </asp:CheckBoxList>
                                </div>
                                <div class="col-md-6">
                                    <asp:CustomValidator ForeColor="red" Style="font-weight: 700;" ClientValidationFunction="ValidateCheckBoxList" ID="CustomValidator1" runat="server" ErrorMessage="Lütfen Profil Seçiniz*"></asp:CustomValidator>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div style="background-color: aquamarine" class="card-header">
                            Birimler
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <br />
                                <div class="col-md-6">

                                    <asp:CheckBoxList CellSpacing="213" ID="ckblBirim" CssClass="chkChoice" runat="server">
                                    </asp:CheckBoxList>
                                </div>
                                <div class="col-md-6">
                                    <asp:CustomValidator ForeColor="red" Style="font-weight: 700;" ClientValidationFunction="ValidateBirim" ID="CustomValidator2" runat="server" ErrorMessage="Lütfen Birim Seçiniz*"></asp:CustomValidator>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div style="background-color: aquamarine" class="card-header">
                            Lokasyonlar
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <br />
                                <div class="col-md-6">

                                    <asp:DropDownList AppendDataBoundItems="true" ID="ddlLokasyon" CssClass="form-control" runat="server">
                                        <asp:ListItem Text="Seçiniz" />
                                    </asp:DropDownList>
                                </div>
                                <div class="col-md-6">

                                    <asp:CompareValidator ID="CompareValidator2" Style="font-weight: 700;" ForeColor="red" ControlToValidate="ddlLokasyon" Type="string" ValueToCompare="Seçiniz" Operator="NotEqual" runat="server" ErrorMessage="Lütfen Person Seçiniz*">
                                        
                                    </asp:CompareValidator>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">

                    <button type="button" onclick="baseUrl();" id="btn_Vazgec" class="btn btn-secondary" data-dismiss="modal">Vazgeç</button>
                    <asp:Button ID="btnNewUser" CssClass="btn btn-success" margin-top="4px;" runat="server" OnClick="btnNewUser_Click" Text="Ekle" />

                </div>
            </div>
        </div>
    </div>



    <div id="snackbar" style="width: 20%; overflow: visible; margin-left: 60%; position: relative; min-height: 40%;">Kayıt Eklendi</div>



    <script>

        function baseUrl() {

            window.location.href = "https://localhost:44398/YONETIM/Kullanicilar";
        }




        function fnConfirmDelete() {
            return confirm("Kullanıcıyı silmek üzeresiniz. Onaylıyor musunuz?");
        }

        //function fnConfirmUpdate() {
        //    return confirm("İş Tanımını güncellemek üzeresiniz. Onaylıyor musunuz?");
        //}






        function MutExChkList(chk) {
            var chkList = chk.parentNode.parentNode.parentNode;
            var chks = chkList.getElementsByTagName("input");
            for (var i = 0; i < chks.length; i++) {
                if (chks[i] != chk && chk.checked) {
                    chks[i].checked = false;
                }
            }
        }


        function ValidateCheckBoxList(source, args) {
            var chklist = document.getElementById('<%= ckblProfil.ClientID %>');
            var chkListinputs = chklist.getElementsByTagName("input");
            for (var i = 0; i < chkListinputs.length; i++) {
                if (chkListinputs[i].checked) {
                    args.IsValid = true;

                    return;
                }
            }
            args.IsValid = false;

        }


        function ValidateBirim(source, args) {
            var chklist = document.getElementById('<%= ckblBirim.ClientID %>');
            var chkListinputs = chklist.getElementsByTagName("input");
            for (var i = 0; i < chkListinputs.length; i++) {
                if (chkListinputs[i].checked) {
                    args.IsValid = true;

                    return;
                }
            }
            args.IsValid = false;

        }



    </script>













    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
</asp:Content>
